#!/bin/bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset

DEVKIT="$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")"
readonly DEVKIT

readonly SCRIPTS="${DEVKIT}/../scripts"
readonly IMAGES="${DEVKIT}/../images"

source "${SCRIPTS}/lib_logging.sh"

declare IMAGE_NAME="build-env"
BUILD_OUTPUT="$("${SCRIPTS}/docker/build.py" "${IMAGE_NAME}" --print-tag --search-path "${IMAGES}")"
readonly BUILD_OUTPUT
BUILD_ENV_IMAGE=$(echo "${BUILD_OUTPUT}" | tail -n 1)
readonly BUILD_ENV_IMAGE

"${SCRIPTS}/docker_run" "${BUILD_ENV_IMAGE}" python3 "${SCRIPTS}/bep.py" "$@"
