#!/bin/bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset

DEVKIT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
readonly DEVKIT

readonly SCRIPTS="${DEVKIT}/../scripts"
source "${SCRIPTS}/lib_logging.sh"

function usage() {
  local -i exitval=${1-1}
  cat &>/dev/stdout << USAGE
usage: $(basename "${BASH_SOURCE[0]}") [--help] [COMMAND] [ARG]...

Runs a command inside the build environment container.

This script provides a containerized build environment with tools like Bazel,
gcloud, buildifier, jq, and more.
If no command is provided, it starts an interactive bash session.

All arguments are passed on to the command executed inside the container.

Options:
  --help                Show this help message and exit.
USAGE
  exit ${exitval}
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --help)
      usage 0
      ;;
    *)
      break
      ;;
  esac
  shift
done

"${SCRIPTS}/build_and_run" build-env "${@:-bash}"
