#!/bin/bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset

DEVKIT="$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")"
readonly DEVKIT

readonly SCRIPTS="${DEVKIT}/../scripts"
readonly IMAGES="${DEVKIT}/../images"

source "${SCRIPTS}/lib_logging.sh"

PROJECT_ROOT="$("${SCRIPTS}/find_project_root")"
readonly PROJECT_ROOT

function usage() {
  local -i exitval=${1-1}
  cat << USAGE
usage: $(basename "${BASH_SOURCE[0]}") [-h] [--suffix SUFFIX]

Validates the bootstrapped project by building it, verifying checksums, and running all tests.
This is done inside the container and on the host.

options:
  -h, --help            Show this help message and exit.
  --suffix SUFFIX       Image suffix.
USAGE
  exit ${exitval}
}

declare SUFFIX=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --suffix)
      SUFFIX="$2"
      shift 2 || usage
      ;;
    -h | --help) usage 0 ;;
    *)
      printf "unrecognized arg: %s\n" "$1"
      usage
      ;;
  esac
done

declare IMAGE_NAME="build-env"
if [[ -n ${SUFFIX} ]]; then
  IMAGE_NAME+="${SUFFIX}"
fi

BUILD_ENV_IMAGE="$("${SCRIPTS}/docker/build.py" "${IMAGE_NAME}" --print-tag --search-path "${IMAGES}" --log-file "${DEVKIT_LOG_FILE}" --config "${PROJECT_ROOT}/devkit.json")" || {
  echo "Build failed. See logs for details: ${DEVKIT_LOG_FILE}" >&2
  exit 1
}
readonly BUILD_ENV_IMAGE

#
# validate the operation of the build* script
#
if "${DEVKIT}/build${SUFFIX}" bash -c "exit 2"; then
  printf "%s failed. Expected non-zero exit\n" "${DEVKIT}/build${SUFFIX}"
  exit 1
fi

"${SCRIPTS}/docker_run" "${BUILD_ENV_IMAGE}" "${SCRIPTS}/test_entrypoint"

# This might fail if Bazel is not installed
"${SCRIPTS}/test_entrypoint" || true
