#!/bin/bash
# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset

function usage() {
  local -i exitval=${1-1}
  cat &>/dev/stdout << USAGE
usage: $(basename "${BASH_SOURCE[0]}") [OPTION]...

This script is the main entrypoint for testing the devkit environment.
It builds the project, verifies checksums, and runs all tests. This script is
not intended to be run directly, but is called by the 'test' script.

Options:
  -h, --help                show this help message and exit

USAGE
  exit ${exitval}
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h | --help) usage 0 ;;
    *) printf "Error: unrecognized arg: %s\n" "$1" ;;
  esac
  shift
done

SCRIPTS="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
readonly SCRIPTS

readonly DEVKIT="${SCRIPTS}/../devkit"

source "${SCRIPTS}/lib_logging.sh"

bazel build //...

"${DEVKIT}/check_checksums"

# This might fail if not tests are present
# TODO: Add some tests into the project
bazel test --config=run_all_tests //... || true
